
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 17 20:39:44 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 18;
  public static final int READ = 6;
  public static final int PLUS = 8;
  public static final int OR = 19;
  public static final int EQUAL = 16;
  public static final int SEMI = 25;
  public static final int CHAR = 5;
  public static final int LEFTPAR = 29;
  public static final int DIFFERENT = 17;
  public static final int GREATER = 12;
  public static final int RIGHTPAR = 30;
  public static final int ID = 23;
  public static final int WRITE = 7;
  public static final int SUB = 9;
  public static final int LESSOREQUAL = 15;
  public static final int COMMA = 27;
  public static final int EOF = 0;
  public static final int GREATEROREQUAL = 14;
  public static final int MAIN = 2;
  public static final int DIV = 11;
  public static final int DOTDOT = 26;
  public static final int CONST = 24;
  public static final int error = 1;
  public static final int ASSIGN = 28;
  public static final int UNTIL = 22;
  public static final int BOOL = 20;
  public static final int INTEGER = 3;
  public static final int RIGHTBRACE = 32;
  public static final int LEFTBRACE = 31;
  public static final int REAL = 4;
  public static final int REPEAT = 21;
  public static final int MUL = 10;
  public static final int LESS = 13;
}

